============================= test session starts ==============================
platform linux -- Python 3.11.4, pytest-7.3.1, pluggy-1.0.0
rootdir: /home/runner/work/week1-devops/week1-devops
plugins: cov-4.1.0
collected 0 items / 1 error
WARNING: Failed to generate report: No data to report.


==================================== ERRORS ====================================
__________________ ERROR collecting tests/test_calculator.py ___________________
ImportError while importing test module '/home/runner/work/week1-devops/week1-devops/tests/test_calculator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_calculator.py:1: in <module>
    from calculator import add, div, mul, sub
E   ModuleNotFoundError: No module named 'calculator'

---------- coverage: platform linux, python 3.11.4-final-0 -----------

=========================== short test summary info ============================
ERROR tests/test_calculator.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.16s ===============================
